services:
  - type: worker
    name: discord-announcer-final
    env: python
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: TZ
        value: Asia/Tokyo
